---
apiVersion: v1
kind: Namespace
metadata:
  name: energie
---
# StorageClass for static local volumes (only create if you don't already have one)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /app
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv1.dockerized.nl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: energie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: my-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: price-pod
  namespace: energie
spec:
  containers:
    - name: energy-scripts
      image: jessemirza/energy-price:0.1
      envFrom:
        - configMapRef:
            name: price-configmap
      volumeMounts:
        - mountPath: /app
          name: app
  volumes:
    - name: app
      persistentVolumeClaim:
        claimName: my-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: price-cronjob
  namespace: energie
spec:
  schedule: "02 15 * * *"
  timeZone: "Europe/Amsterdam"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: get-price2
              image: jessemirza/energy-price:0.1
              imagePullPolicy: IfNotPresent
              command: ["python3", "/app/price.py"]
              volumeMounts:
                - mountPath: /app
                  name: app
          volumes:
            - name: app
              persistentVolumeClaim:
                claimName: my-pvc

