apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami   # external Helm repo
    chart: owncloud                              # chart name
    targetRevision: 12.2.15                      # version from 'helm search repo bitnami/owncloud'
    helm:
      values: |
        ingress.enabled: true
        ingress.hostname: owncloud.example.com
        existingSecret: owncloud-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

